### ISSUE TITLE
Database Schema Feedback

### ISSUE THREAD

**Issue by ssvillarosa** [PUP-BSIT/project-quantech#3]
You don't need a database. I intended you to not have a backend so you will no longer need a database. You should manipulate and present data from the logistics app. Kindly coordinate with them.
Also, remind your groupmate Fernandez to sign up for our GitHub account. If she will not cooperate with you, I will assign her her own project.

**Comment by alima-kailamarie** [comment]
Noted sir, thankyouu!! And about Ms. Fernandez she already made an account in the github repo that we gave.

**Comment by ssvillarosa** [comment]
All good! Closing this ticket.
