### ISSUE TITLE
Mockups Feedback

### ISSUE THREAD

**Issue by ssvillarosa** [PUP-BSIT/project-quantech#4]
Among all groups, you are the only one that provide a link instead of a screenshot. This is unacceptable and an irresponsible act. I'm giving 2 demerit points to all members of this group.

**Comment by alima-kailamarie** [comment]
Good evening sir, we appreciate your feedback and we're sorry for the inconvenience. We already uploaded the screenshots of our mock ups in the documents folder. Thankyouu!!

**Comment by ssvillarosa** [comment]
I will review again your mock ups once you uploaded it. For the mean time, please keep this ticket open. Once you have uploaded, please let me know.

**Comment by alima-kailamarie** [comment]
Okay sir, we will update you.

**Comment by alima-kailamarie** [comment]
Good afternoon sir we already uploaded the updated mock ups, you can review it. Thankyouu!!

**Comment by ssvillarosa** [comment]
Hi Quantech group,

So when your app opens, this screen will load:

![image](https://github.com/PUP-BSIT/project-quantech/assets/76401444/54da85fa-b428-4bae-86b2-2750591c2367)

I will call it the homepage. The list should display the items that are not yet delivered so I'm a bit confused about the delivery date. Does it refer to when the parcel is supposed to be delivered? Or I guess it's supposed to be the actual delivery date? Either way, the delivery date is irrelevant to the rider since the list contains only the items that are not yet delivered.
For a delivery rider, a Tracking ID and Customer ID is not relevant. A more relevant column to display should be the receiver name and the receiver's address. 

-----

If I understand it correctly, the screen below would show when I select any row in the homepage.

![image](https://github.com/PUP-BSIT/project-quantech/assets/76401444/ddf5f189-a585-402d-84c8-6d849d1758d5)

So when you click a row, you will be shown the order details. Why does the button says "Track Status"? The rider should be the one to update the status. So instead of "Track Status", make it "Update Status". It would also be good if you place the map here instead, indicating the destination of the order. 

------

Now when the user click "Update Status", the user will be shown this screen:

![image](https://github.com/PUP-BSIT/project-quantech/assets/76401444/712af91a-6f8e-4221-94ef-8dc19fdfb03e)

Based on the content, the user will update only the status of the order(Sorting Center, In transit, Delivered). Kindly check for the parameters of the update-delivery() API. How are you supposed to add the checkpoint_location and description? Will you be using Geolocation of Javascript to get the user's location?

![image](https://github.com/PUP-BSIT/project-quantech/assets/76401444/1be1ff72-d53e-4b65-b806-eff92bd1c18c)

-------

I don't understand these part and the delivery logs.
![image](https://github.com/PUP-BSIT/project-quantech/assets/76401444/56a0464d-c759-4a0d-ae96-62b6239d769c)

-----

To make it clear to you, let's say I have a delivery parcel(delivery  with id 789) received from Paranaque to Gen Tri. Say it's path will cross 3 checkpoint locations namely Paranaque->Alabang->Gen Tri. 

In the delivery process, there will be 3 checkpoints that will be involved:
1. The rider will pick up from the parcel from Paranaque. Upon pick up, rider will call the update-delivery() API with a description "Picked up from seller" with a corresponding timestamp and checkpoint location(Paranaque).
2.  Rider will then deliver this to the next checkpoint location point which is in Alabang. Upon arriving in Alabang, the rider will call the update-delivery() API again to add another checkpoint "Alabang" with time stamp and a description say "In transit".
3. The rider will continue his drive to Gen Tri. Upon arriving, the rider will call the update-delivery() API again to add another checkpoint "Gen Tri" with timestamp and a description say "In transit".
4. The rider will now deliver to the door step of the recipient. Upon delivery, the rider will call the update-delivery() API again to update the status to "Completed" with timestamp and description say "Delivered"

I know this is far from the real scenario. When I made this project, what I have in my mind is that every checkpoint has different rider so that in one delivery, there will be 3 riders involved. However, this will complicate the architecture both the logistics and the delivery partner. And the risk that you might not finish it on-time. For the sake of completing the project, I lessen its complexity to the above scenario. However, I am expecting more from you to compensate this simplification.

Kindly cascade this to logistics group, Cybertech so to make sure that we are in the same page.

**Comment by alima-kailamarie** [comment]
Noted sir. Thank you for your feedback. We're going to make the modifications you've mentioned and we will cascade this information to the logistics group.

**Comment by alima-kailamarie** [comment]
Goodevening sir, we already updated our netlify. So you can browse our homepage but the login page, order details and tracking page not included first because the user credentials and other data will be given tomorrow and thursday, as logistics group said.

**Comment by alima-kailamarie** [comment]
okay po sir, thank you.
